
import "./styles/doubt.css"

export const Doubt = () => {
  return (
    <div className="doubt">
      <h2>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis ex culpa illo?</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores doloremque est ipsum quos incidunt culpa vero modi! Reiciendis commodi modi, a velit error, alias aspernatur tenetur doloribus, similique perferendis voluptate. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat deleniti excepturi eos eveniet cumque, itaque provident enim adipisci reprehenderit aliquam voluptatum, voluptatem architecto, eaque distinctio doloribus repudiandae unde labore delectus? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit commodi distinctio quo amet corrupti eos possimus, doloribus, deserunt quasi blanditiis velit molestias rerum quas praesentium, quae inventore modi nam error. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit ullam sed eum ipsam alias. At pariatur aspernatur, nostrum, aperiam eius fugiat nisi voluptatem est eligendi nesciunt hic tempora nam harum!</p>
      <h2>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis ex culpa illo?</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores doloremque est ipsum quos incidunt culpa vero modi! Reiciendis commodi modi, a velit error, alias aspernatur tenetur doloribus, similique perferendis voluptate. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat deleniti excepturi eos eveniet cumque, itaque provident enim adipisci reprehenderit aliquam voluptatum, voluptatem architecto, eaque distinctio doloribus repudiandae unde labore delectus? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit commodi distinctio quo amet corrupti eos possimus, doloribus, deserunt quasi blanditiis velit molestias rerum quas praesentium, quae inventore modi nam error. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit ullam sed eum ipsam alias. At pariatur aspernatur, nostrum, aperiam eius fugiat nisi voluptatem est eligendi nesciunt hic tempora nam harum!</p>
      <h2>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis ex culpa illo?</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores doloremque est ipsum quos incidunt culpa vero modi! Reiciendis commodi modi, a velit error, alias aspernatur tenetur doloribus, similique perferendis voluptate. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat deleniti excepturi eos eveniet cumque, itaque provident enim adipisci reprehenderit aliquam voluptatum, voluptatem architecto, eaque distinctio doloribus repudiandae unde labore delectus? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit commodi distinctio quo amet corrupti eos possimus, doloribus, deserunt quasi blanditiis velit molestias rerum quas praesentium, quae inventore modi nam error. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit ullam sed eum ipsam alias. At pariatur aspernatur, nostrum, aperiam eius fugiat nisi voluptatem est eligendi nesciunt hic tempora nam harum!</p>
        <div className="end">
          <h2>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis ex culpa illo?</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores doloremque est ipsum quos incidunt culpa vero modi! Reiciendis commodi modi, a velit error, alias aspernatur tenetur doloribus, similique perferendis voluptate. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat deleniti excepturi eos eveniet cumque, itaque provident enim adipisci reprehenderit aliquam voluptatum, voluptatem architecto, eaque distinctio doloribus repudiandae unde labore delectus? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit commodi distinctio quo amet corrupti eos possimus, doloribus, deserunt quasi blanditiis velit molestias rerum quas praesentium, quae inventore modi nam error. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit ullam sed eum ipsam alias. At pariatur aspernatur, nostrum, aperiam eius fugiat nisi voluptatem est eligendi nesciunt hic tempora nam harum!</p>
        </div>
    </div>
  )
}
